services:
  api:
    container_name: "api"
    build: ./UsCore
    restart: always
    volumes:
      - ./UsCore:/app
    networks:
      - api-db
    env_file:
      - .env-non-dev
    expose:
      - 8000
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: "db"
    image: postgres
    networks:
      - api-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - "5432:5432"


networks:
  api-db:

volumes:
  pgdata:
