import os

from dotenv import load_dotenv
load_dotenv()

POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_NAME = os.getenv('POSTGRES_NAME')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')

POSTGRES_TEST_USER = os.getenv('POSTGRES_TEST_USER')
POSTGRES_TEST_PASSWORD = os.getenv('POSTGRES_TEST_PASSWORD')
POSTGRES_TEST_NAME = os.getenv('POSTGRES_TEST_NAME')
POSTGRES_TEST_PORT = os.getenv('POSTGRES_TEST_PORT')
POSTGRES_TEST_HOST = os.getenv('POSTGRES_TEST_HOST')
